# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/opencontainers/runtime-spec/8f3fbc881602d85699e5c448634ec1288860d966/schema/features-schema.json
#   timestamp: 2024-08-12T10:26:47+00:00

from __future__ import annotations

from collections.abc import Sequence


from pyoci.common import Annotations
from msgspec import Struct

from pyoci.platform.linux.runtime_features import LinuxFeatures


class Features(Struct):
    ociVersionMin: str
    ociVersionMax: str
    hooks: Sequence[str] | None = None
    mountOptions: Sequence[str] | None = None
    annotations: Annotations | None = None
    potentiallyUnsafeConfigAnnotations: Sequence[str] | None = None
    linux: LinuxFeatures | None = None
